image:
  pullPolicy: IfNotPresent
  repository: docker.io/plexripper/plexripper
  tag: 0.24.0@sha256:23aaa8fcdfe8ec7d3baf937ee608337644b74d359ffdb485005b604cf50348f6
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 7000
        port: 7000
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: http
            readiness:
              enabled: true
              type: http
            startup:
              enabled: true
              type: http
persistence:
  config:
    enabled: true
    mountPath: /Config
  downloads:
    enabled: true
    mountPath: /Downloads
portal:
  open:
    enabled: true
