name: clustertool-go-release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    tags:
      - "*"
    paths:
      - 'clustertool/**'
jobs:
  goreleaser:
    runs-on: actions-runners
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum
      # - name: Install Syft
      #   run: sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6
        with:
          args: release --clean
          distribution: goreleaser # or 'goreleaser-pro'
          version: "~> v2" # or 'latest', 'nightly', semver
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
